# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x06loomic\"\x90\x01\n\x0b\x43hatMessage\x12\x0e\n\x06msg_id\x18\x01 \x01(\x04\x12\x11\n\tsender_id\x18\x02 \x01(\x04\x12\x14\n\x0crecipient_id\x18\x03 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12!\n\x04type\x18\x06 \x01(\x0e\x32\x13.loomic.MessageType*7\n\x0bMessageType\x12\x08\n\x04\x43HAT\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\x08\n\x04PING\x10\x02\x12\x08\n\x04PONG\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=169
  _globals['_MESSAGETYPE']._serialized_end=224
  _globals['_CHATMESSAGE']._serialized_start=23
  _globals['_CHATMESSAGE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
