services:
  server:
    image: ${GAR_IMAGE}
    ports:
      - "7777:7777"
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./certs:/app/certs
    env_file:
      - .env
    restart: unless-stopped
