#include "LoomicServer/tcp/Session.hpp"
#include "LoomicServer/tcp/SessionRegistry.hpp"
#include "LoomicServer/auth/JwtService.hpp"
#include "LoomicServer/auth/SnowflakeGen.hpp"
#include "LoomicServer/db/RedisClient.hpp"
#include "LoomicServer/db/CassandraClient.hpp"
#include "LoomicServer/util/Logger.hpp"

// Generated by CMake protobuf_generate_cpp from proto/chat.proto
#include "chat.pb.h"

#include <chrono>
#include <cstring>
#include <string>

#include <boost/asio/co_spawn.hpp>
#include <boost/asio/detached.hpp>
#include <boost/asio/post.hpp>
#include <boost/asio/redirect_error.hpp>
#include <boost/asio/use_awaitable.hpp>
#include <boost/asio/write.hpp>

namespace Loomic {

namespace net = boost::asio;

// ── TokenBucket ───────────────────────────────────────────────────────────────

bool TokenBucket::consume()
{
    using namespace std::chrono;
    auto   now     = steady_clock::now();
    double elapsed = duration<double>(now - last_refill).count();
    last_refill    = now;
    tokens         = std::min(max_tokens, tokens + elapsed * refill_rate);
    if (tokens >= 1.0) {
        tokens -= 1.0;
        return true;
    }
    return false;
}

// ── Session ───────────────────────────────────────────────────────────────────

Session::Session(SslStream                        socket,
                 std::shared_ptr<SessionRegistry> registry,
                 std::shared_ptr<JwtService>      jwt,
                 std::shared_ptr<RedisClient>     redis,
                 std::shared_ptr<CassandraClient> cass,
                 std::shared_ptr<SnowflakeGen>    snowflake)
    : socket_(std::move(socket))
    , strand_(net::make_strand(socket_.get_executor()))
    , heartbeat_(strand_)
    , registry_(std::move(registry))
    , jwt_(std::move(jwt))
    , redis_(std::move(redis))
    , cass_(std::move(cass))
    , snowflake_(std::move(snowflake))
{}

net::awaitable<void> Session::run()
{
    // Keep the Session alive for the entire duration of this coroutine.
    auto self = shared_from_this();

    try {
        // ── Step 1: AUTH frame ────────────────────────────────────────────
        auto auth_hdr = co_await read_frame_header(socket_);
        if (static_cast<MsgType>(auth_hdr.msg_type) != MsgType::AUTH) {
            co_return; // First frame must be AUTH; drop the connection.
        }
        if (auth_hdr.payload_len > 4096) {
            co_return; // Suspiciously large token; drop.
        }

        auto auth_payload = co_await read_frame_payload(socket_, auth_hdr.payload_len);
        std::string token(auth_payload.begin(), auth_payload.end());

        auto user = jwt_->verify(token);
        if (!user) {
            FrameHeader err{};
            err.msg_type = static_cast<uint8_t>(MsgType::ERROR);
            co_await write_frame(socket_, err, {});
            co_return;
        }
        user_id_ = static_cast<uint64_t>(user->uid);
        registry_->insert(user_id_, self);

        // ── Step 2: deliver any offline messages ──────────────────────────
        co_await flush_offline_queue();

        // ── Step 3: start heartbeat supervisor ────────────────────────────
        net::co_spawn(strand_, heartbeat_loop(), net::detached);

        // ── Step 4: message loop ──────────────────────────────────────────
        for (;;) {
            auto hdr  = co_await read_frame_header(socket_);
            auto type = static_cast<MsgType>(hdr.msg_type);

            if (type == MsgType::PING) {
                reset_heartbeat();
                FrameHeader pong{};
                pong.msg_type = static_cast<uint8_t>(MsgType::PONG);
                co_await write_frame(socket_, pong, {});

            } else if (type == MsgType::CHAT) {
                if (hdr.payload_len > (1u << 20)) {
                    co_return; // 1 MiB max; drop runaway sender.
                }
                auto payload = co_await read_frame_payload(socket_, hdr.payload_len);

                if (rate_limiter_.consume()) {
                    co_await route_message(hdr, std::move(payload));
                } else {
                    FrameHeader err{};
                    err.msg_type = static_cast<uint8_t>(MsgType::ERROR);
                    co_await write_frame(socket_, err, {});
                }

            } else {
                // Unknown type: drain payload to keep stream in sync, then ignore.
                if (hdr.payload_len > 0 && hdr.payload_len <= (1u << 20)) {
                    co_await read_frame_payload(socket_, hdr.payload_len);
                }
            }
        }
    } catch (const boost::system::system_error& e) {
        if (e.code() != net::error::operation_aborted &&
            e.code() != net::error::eof) {
            LOG_WARN("Session {}: disconnected: {}", user_id_, e.what());
        }
    } catch (const std::exception& e) {
        LOG_WARN("Session {}: error: {}", user_id_, e.what());
    }

    // ── Cleanup ───────────────────────────────────────────────────────────
    heartbeat_.cancel();
    if (user_id_ != 0) {
        registry_->remove(user_id_);
    }
}

net::awaitable<void> Session::flush_offline_queue()
{
    auto self   = shared_from_this();
    auto key    = "offline:" + std::to_string(user_id_);
    auto frames = co_await redis_->lrange_and_del(key);
    for (auto& frame : frames) {
        enqueue(std::move(frame));
    }
}

net::awaitable<void> Session::heartbeat_loop()
{
    auto self = shared_from_this();
    try {
        for (;;) {
            heartbeat_.expires_after(std::chrono::seconds(30));
            boost::system::error_code ec;
            co_await heartbeat_.async_wait(
                net::redirect_error(net::use_awaitable, ec));
            if (!ec) {
                // Timer fired without being reset — connection is stale.
                LOG_WARN("Session {}: heartbeat timeout, closing connection", user_id_);
                boost::system::error_code close_ec;
                socket_.lowest_layer().close(close_ec);
                co_return;
            }
            // ec == operation_aborted means reset_heartbeat() was called (PING).
        }
    } catch (...) {}
}

void Session::reset_heartbeat()
{
    heartbeat_.cancel();
}

net::awaitable<void> Session::route_message(const FrameHeader& hdr,
                                             std::vector<uint8_t> payload)
{
    auto self = shared_from_this();

    uint64_t msg_id = static_cast<uint64_t>(snowflake_->next());
    int64_t  ts_ms  = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();

    // Serialize message as a protobuf ChatMessage.
    loomic::ChatMessage msg;
    msg.set_msg_id(msg_id);
    msg.set_sender_id(user_id_);
    msg.set_recipient_id(hdr.recipient_id);
    msg.set_content(payload.data(), payload.size());
    msg.set_timestamp_ms(ts_ms);
    msg.set_type(loomic::CHAT);

    std::string proto_bytes = msg.SerializeAsString();

    // Build the outgoing wire frame: FrameHeader + serialized protobuf.
    FrameHeader out{};
    out.payload_len  = static_cast<uint32_t>(proto_bytes.size());
    out.msg_type     = static_cast<uint8_t>(MsgType::CHAT);
    out.msg_id       = msg_id;
    out.sender_id    = user_id_;
    out.recipient_id = hdr.recipient_id;

    std::vector<uint8_t> frame_bytes(sizeof(FrameHeader) + proto_bytes.size());
    std::memcpy(frame_bytes.data(), &out, sizeof(FrameHeader));
    std::memcpy(frame_bytes.data() + sizeof(FrameHeader),
                proto_bytes.data(), proto_bytes.size());

    // Deliver: online path (strand-safe post) or offline path (Redis).
    auto recipient = registry_->lookup(hdr.recipient_id);
    if (recipient) {
        net::post(recipient->strand(),
                  [recipient, fb = frame_bytes]() mutable {
                      recipient->enqueue(std::move(fb));
                  });
    } else {
        co_await redis_->lpush("offline:" + std::to_string(hdr.recipient_id),
                               std::span<const uint8_t>(frame_bytes));
    }

    // Persist to Cassandra regardless of online/offline status.
    cass_->store_message(
        hdr.recipient_id, msg_id, user_id_,
        std::span<const uint8_t>(
            reinterpret_cast<const uint8_t*>(proto_bytes.data()),
            proto_bytes.size()),
        ts_ms, static_cast<uint8_t>(MsgType::CHAT));
}

void Session::enqueue(std::vector<uint8_t> frame)
{
    // Called on strand_ only (via net::post from route_message or flush).
    write_queue_.push_back(std::move(frame));
    if (!writing_) {
        writing_ = true;
        net::co_spawn(strand_, do_write(), net::detached);
    }
}

net::awaitable<void> Session::do_write()
{
    auto self = shared_from_this();
    try {
        while (!write_queue_.empty()) {
            // Move the front frame out before awaiting so enqueue() can safely
            // add to write_queue_ while the async_write is in flight.
            auto frame = std::move(write_queue_.front());
            write_queue_.pop_front();
            co_await net::async_write(socket_, net::buffer(frame),
                                      net::use_awaitable);
        }
    } catch (const std::exception& e) {
        LOG_WARN("Session {}: write error: {}", user_id_, e.what());
    }
    writing_ = false;
}

} // namespace Loomic
